<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\Inspection;

class InspectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('inspections')->insert([
            [
                'production_id' => 1,
                'production_date' => '2026-05-01',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-02',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-03',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-04',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-05',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-06',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-07',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-08',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-08',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-09',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-10',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-11',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-12',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-13',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-14',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-05-15',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-01',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-02',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-03',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-04',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-05',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-06',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-07',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-08',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-08',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-09',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-10',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-11',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-12',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-13',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-14',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-05-15',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-01',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-02',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-03',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-04',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-05',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-06',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-07',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-08',
                'user_id' => 1,
                'shipment_date' => '2026-07-10',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-08',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-09',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-10',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-11',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-12',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-13',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-14',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 3,
                'production_date' => '2026-05-15',
                'user_id' => 1,
                'shipment_date' => '2026-07-11',
                'inspection_date' => '2026-06-01',
                'measurement' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-06-07',
                'user_id' => null,
                'shipment_date' => '2026-07-10',
                'inspection_date' => null,
                'measurement' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 2,
                'production_date' => '2026-06-08',
                'user_id' => null,
                'shipment_date' => '2026-07-08',
                'inspection_date' => null,
                'measurement' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-06-09',
                'user_id' => null,
                'shipment_date' => '2026-07-07',
                'inspection_date' => null,
                'measurement' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'production_id' => 1,
                'production_date' => '2026-06-10',
                'user_id' => null,
                'shipment_date' => '2026-07-05',
                'inspection_date' => null,
                'measurement' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
